apiVersion: v1
kind: Secret
metadata:
  name: keller-rejas-32-secret
  namespace: keller-rejas-32
  labels:
    app: consumo-apis
    name: keller-rejas-32-secret
type: Opaque
data:
  # Base64 encoded values
  # mongodb+srv://kellerrejas_db_user:T6NwrDiXbfIBvCRA@mycluster.bee1ylw.mongodb.net/15_keller_rejas?appName=MyCluster
  MONGODB_URI: bW9uZ29kYitzcnY6Ly9rZWxsZXJyZWphc19kYl91c2VyOlQ2TndyRGlYYmZJQnZDUkFAbXljbHVzdGVyLmJlZTF5bHcubW9uZ29kYi5uZXQvMTVfa2VsbGVyX3JlamFzP2FwcE5hbWU9TXlDbHVzdGVy
  # 82b52b3434msh84355d1fee2ef45p1ae74cjsnffcd418fadaa
  RAPIDAPI_KEY: ODJiNTJiMzQzNG1zaDg0MzU1ZDFmZWUyZWY0NXAxYWU3NGNqc25mZmNkNDE4ZmFkYWE=
  # https://google-map-places-new-v2.p.rapidapi.com
  GOOGLE_MAPS_BASE_URL: aHR0cHM6Ly9nb29nbGUtbWFwLXBsYWNlcy1uZXctdjIucC5yYXBpZGFwaS5jb20=
  # https://ip-geo-location10.p.rapidapi.com
  IP_GEO_BASE_URL: aHR0cHM6Ly9pcC1nZW8tbG9jYXRpb24xMC5wLnJhcGlkYXBpLmNvbQ==
