apiVersion: v1
kind: Service
metadata:
  name: keller-rejas-32-service
  namespace: keller-rejas-32
  labels:
    app: consumo-apis
    name: keller-rejas-32-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: consumo-apis
    name: keller-rejas-32-deployment
